### ISSUE TITLE
Request: support on Linux/ARM

### ISSUE THREAD

**Issue by KenDickey** [guillermoamaral/Webside#69]
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/home/pi/Webside/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/pi/Webside/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/pi/Webside/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/pi/Webside/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/pi/Webside/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/pi/Webside/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/pi/Webside/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/pi/Webside/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/home/pi/Webside/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/home/pi/Webside/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/pi/Webside/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/pi/Webside/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/pi/Webside/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/pi/Webside/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/pi/Webside/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/pi/Webside/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/pi/Webside/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.10.0

Raspian:RasPi4:~/Webside >>> uname -a
Linux Raspian4 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

Raspian:RasPi4:~/Webside >>>

**Comment by KenDickey** [comment]
I am able to use Webside on an aarch64/arm64 Pinebook.
So the problem is for a RasPi4/Raspian.
I did do the `npm install npm@latest -g` prior to test.
Not a node/npm user, so fairly clueless.

**Comment by guillermoamaral** [comment]
Hi, I'm have no idea what can be causing that. I searched the web and found this https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported.

**Comment by KenDickey** [comment]
Yes.  Did some combo of
  sudo npm audit fix
  sudo npm update
  sudo npm audit fix --force
And Webside now up on RasPi4/Raspian.

Thanks!
